CREATE DATABASE SportsStore;

USE [SportsStore];

CREATE TABLE Users (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    username VARCHAR(40) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE Carts (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	userId UNIQUEIDENTIFIER UNIQUE NOT NULL,
	FOREIGN  KEY(userId) REFERENCES Users(id)
);

CREATE TABLE Categories (
	id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	name VARCHAR(100) NOT NULL
);

CREATE TABLE Products (
	id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	name VARCHAR(100) NOT NULL,
	description VARCHAR(500) NOT NULL,
	categoryId UNIQUEIDENTIFIER NOT NULL,
	price MONEY NOT NULL,

	FOREIGN KEY (categoryId) REFERENCES Categories(id)
);

CREATE TABLE Orders (
	id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	userId UNIQUEIDENTIFIER NOT NULL,
	name VARCHAR(100) NOT NULL,
	street VARCHAR(100) NOT NULL,
	city VARCHAR(100) NOT NULL,
	state VARCHAR(100) NOT NULL,
	zip VARCHAR(20) NOT NULL,
	country VARCHAR(50) NOT NULL,
	giftwrap BIT NOT NULL,

	FOREIGN KEY (userId) REFERENCES [Users](id)
);

CREATE TABLE OrderDetails (
	id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	orderId UNIQUEIDENTIFIER FOREIGN KEY (orderId) REFERENCES Orders(id),
	productId UNIQUEIDENTIFIER  FOREIGN KEY (productId) REFERENCES Products(id),
);


CREATE TABLE CartItems (
	id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	cartId UNIQUEIDENTIFIER NOT NULL,
	productId UNIQUEIDENTIFIER NOT NULL,
	
	FOREIGN KEY (cartId) REFERENCES Carts (id),
	FOREIGN KEY (productId) REFERENCES Products(id)
);
